Repository prgrms-be-devcourse/NBE3-4-3-Team03, pull requests merged in 2025-03, with the labels that each got.

#9 #1 test - 견적 도메인의 Service 레이어 테스트 코드 추가
  backend/src/main/java/com/programmers/pcquotation/domain/category/entity/Category.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/dto/EstimateCreateRequest.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/dto/EstimateItemDto.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/dto/EstimateUpdateReqDto.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/entity/Estimate.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/service/EstimateService.java
  backend/src/main/java/com/programmers/pcquotation/domain/item/entity/Item.java
  backend/src/test/java/com/programmers/pcquotation/estimate/controller/EstimateControllerTest.java
  backend/src/test/java/com/programmers/pcquotation/estimate/service/EstimateServiceTest.java
Labels: test

#18 #2 fix - 견적 도메인의 Entity, Service, DTO를 Kotlin으로 변환
  backend/build.gradle
  backend/src/main/java/com/programmers/pcquotation/domain/comment/emtity/Comment.java
  backend/src/main/java/com/programmers/pcquotation/domain/comment/service/CommentService.java
  backend/src/main/java/com/programmers/pcquotation/domain/delivery/service/DeliveryService.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/controller/EstimateController.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/dto/EstimateAllResDto.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/dto/EstimateCreateRequest.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/dto/EstimateCreateRequest.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/dto/EstimateForCustomerResponse.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/dto/EstimateForSellerResponse.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/dto/EstimateItemDto.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/dto/EstimateItemDto.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/dto/EstimateSellerResDto.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/dto/EstimateUpdateReqDto.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/dto/EstimateUpdateReqDto.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/dto/ReceivedQuoteDTO.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/entity/Estimate.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/entity/Estimate.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/entity/EstimateComponent.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/entity/EstimateComponent.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/repository/EstimateRepository.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/service/EstimateService.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/service/EstimateService.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/entity/EstimateRequest.java
  backend/src/main/java/com/programmers/pcquotation/domain/item/repository/ItemRepository.java
  backend/src/main/java/com/programmers/pcquotation/global/security/SecurityConfig.java
  backend/src/test/java/com/programmers/pcquotation/estimate/controller/EstimateControllerTest.java
  backend/src/test/java/com/programmers/pcquotation/estimate/service/EstimateServiceTest.java
  frontend/src/app/customers/info/page.js
  frontend/src/app/estimate/create/page.js
  frontend/src/app/sellers/info/page.js
Labels: fix, refactor

#30 Feature/#24 부품 엔티티, 서비스 코틀린 변환
  backend/build.gradle
  backend/src/main/java/com/programmers/pcquotation/domain/category/dto/CategoryCreateRequest.kt
  backend/src/main/java/com/programmers/pcquotation/domain/category/dto/CategoryCreateResponse.java
  backend/src/main/java/com/programmers/pcquotation/domain/category/dto/CategoryCreateResponse.kt
  backend/src/main/java/com/programmers/pcquotation/domain/category/dto/CategoryDeleteResponse.java
  backend/src/main/java/com/programmers/pcquotation/domain/category/dto/CategoryDeleteResponse.kt
  backend/src/main/java/com/programmers/pcquotation/domain/category/dto/CategoryInfoResponse.java
  backend/src/main/java/com/programmers/pcquotation/domain/category/dto/CategoryInfoResponse.kt
  backend/src/main/java/com/programmers/pcquotation/domain/category/dto/CategoryUpdateRequest.kt
  backend/src/main/java/com/programmers/pcquotation/domain/category/dto/CategoryUpdateResponse.java
  backend/src/main/java/com/programmers/pcquotation/domain/category/dto/CategoryUpdateResponse.kt
  backend/src/main/java/com/programmers/pcquotation/domain/category/entity/Category.java
  backend/src/main/java/com/programmers/pcquotation/domain/category/entity/Category.kt
  backend/src/main/java/com/programmers/pcquotation/domain/category/service/CategoryService.java
  backend/src/main/java/com/programmers/pcquotation/domain/category/service/CategoryService.kt
  backend/src/main/java/com/programmers/pcquotation/domain/item/dto/ItemInfoResponse.java
  backend/src/main/java/com/programmers/pcquotation/domain/item/dto/ItemInfoResponse.kt
  backend/src/main/java/com/programmers/pcquotation/domain/item/entity/Item.java
  backend/src/main/java/com/programmers/pcquotation/domain/item/entity/Item.kt
  backend/src/main/java/com/programmers/pcquotation/domain/item/service/ItemService.java
  backend/src/main/java/com/programmers/pcquotation/domain/item/service/ItemService.kt
  backend/src/test/java/com/programmers/pcquotation/domain/category/service/CategoryServiceTest.java
  backend/src/test/java/com/programmers/pcquotation/domain/item/service/ImageServiceTest.java
  backend/src/test/java/com/programmers/pcquotation/domain/item/service/ItemServiceTest.java
  backend/src/test/java/com/programmers/pcquotation/estimate/service/EstimateServiceTest.java
  backend/src/test/java/com/programmers/pcquotation/util/TestCategoryFactory.kt
  backend/src/test/java/com/programmers/pcquotation/util/TestItemFactory.kt
Labels: fix, refactor, test

#34 #25 fix - 견적 Repository 및 Controller를 Kotlin으로 변환, DTO 및 엔드포인트 수정, 부품 조회 코드 수정
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/controller/EstimateController.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/controller/EstimateController.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/dto/EstimateForSellerResponse.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/dto/EstimateResponse.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/dto/ItemInfoDto.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/entity/Estimate.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/repository/EstimateRepository.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/repository/EstimateRepository.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/service/EstimateService.kt
  backend/src/main/java/com/programmers/pcquotation/domain/item/service/ItemService.kt
  backend/src/test/java/com/programmers/pcquotation/estimate/controller/EstimateControllerTest.java
  backend/src/test/java/com/programmers/pcquotation/estimate/service/EstimateServiceTest.java
  frontend/src/app/customers/info/page.js
  frontend/src/app/sellers/info/page.js
Labels: fix

#49 #47 fix - 누락된 Config 클래스 추가
  backend/src/main/java/com/programmers/pcquotation/global/cache/CacheConfig.kt
Labels: fix

#51 Feature/#39 관리자 로그아웃, 페이징, 정렬 기능 구현
  backend/build.gradle
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/controller/EstimateController.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/dto/EstimateRequestResponse.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/dto/EstimateSortType.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/entity/Estimate.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/repository/EstimateRepository.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/service/EstimateService.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/controller/EstimateRequestController.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/repository/EstimateRequestRepository.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/service/EstimateRequestService.java
  backend/src/main/resources/data.sql
  backend/src/test/java/com/programmers/pcquotation/estimate/service/EstimateServiceTest.java
  frontend/src/app/admin/management/page.js
  frontend/src/app/customers/info/page.js
  frontend/src/app/sellers/info/page.js
Labels: feature

#35 Feature/#8 알림 기능 구현
  backend/.gitignore
  backend/src/main/java/com/programmers/pcquotation/PcquotationApplication.java
  backend/src/main/java/com/programmers/pcquotation/domain/alarm/AlarmEntity.kt
  backend/src/main/java/com/programmers/pcquotation/domain/alarm/AlarmRepository.kt
  backend/src/main/java/com/programmers/pcquotation/domain/alarm/controller/AlarmController.kt
  backend/src/main/java/com/programmers/pcquotation/domain/alarm/service/AlarmService.kt
  backend/src/main/java/com/programmers/pcquotation/domain/alarm/service/AlarmStrategy.java
  backend/src/main/java/com/programmers/pcquotation/domain/customer/repository/CustomerRepository.kt
  backend/src/main/java/com/programmers/pcquotation/domain/delivery/controller/DeliveryController.java
  backend/src/main/java/com/programmers/pcquotation/domain/delivery/controller/DeliveryController.kt
  backend/src/main/java/com/programmers/pcquotation/domain/delivery/entity/Delivery.java
  backend/src/main/java/com/programmers/pcquotation/domain/delivery/entity/Delivery.kt
  backend/src/main/java/com/programmers/pcquotation/domain/delivery/entity/DeliveryCreateRequest.java
  backend/src/main/java/com/programmers/pcquotation/domain/delivery/entity/DeliveryCreateRequest.kt
  backend/src/main/java/com/programmers/pcquotation/domain/delivery/entity/DeliveryDto.java
  backend/src/main/java/com/programmers/pcquotation/domain/delivery/entity/DeliveryDto.kt
  backend/src/main/java/com/programmers/pcquotation/domain/delivery/entity/DeliveryStatus.java
  backend/src/main/java/com/programmers/pcquotation/domain/delivery/entity/DeliveryStatus.kt
  backend/src/main/java/com/programmers/pcquotation/domain/delivery/exception/DeliveryExceptionHandler.java
  backend/src/main/java/com/programmers/pcquotation/domain/delivery/exception/DeliveryExceptionHandler.kt
  backend/src/main/java/com/programmers/pcquotation/domain/delivery/exception/NullEntityException.java
  backend/src/main/java/com/programmers/pcquotation/domain/delivery/exception/NullEntityException.kt
  backend/src/main/java/com/programmers/pcquotation/domain/delivery/repository/DeliveryRepository.java
  backend/src/main/java/com/programmers/pcquotation/domain/delivery/repository/DeliveryRepository.kt
  backend/src/main/java/com/programmers/pcquotation/domain/delivery/service/DeliveryService.java
  backend/src/main/java/com/programmers/pcquotation/domain/delivery/service/DeliveryService.kt
  backend/src/main/java/com/programmers/pcquotation/domain/delivery/service/DeliveryServiceByJpa.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/controller/EstimateController.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimate/service/EstimateService.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/controller/EstimateRequestController.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/controller/EstimateRequestController.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/dto/EstimateRequestData.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/dto/EstimateRequestData.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/dto/EstimateRequestReqDto.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/dto/EstimateRequestResDto.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/dto/EstimateRequestResDto.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/entity/EstimateRequest.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/entity/EstimateRequest.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/entity/EstimateRequestStatus.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/entity/EstimateRequestStatus.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/exception/EstimateRequestExceptionHandler.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/exception/EstimateRequestExceptionHandler.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/repository/EstimateRequestRepository.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/repository/EstimateRequestRepository.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/service/EstimateRequestService.java
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/service/EstimateRequestService.kt
  backend/src/main/java/com/programmers/pcquotation/domain/estimaterequest/service/EstimateRequestServiceByJpa.kt
  backend/src/main/java/com/programmers/pcquotation/domain/member/service/AuthService.kt
  backend/src/main/java/com/programmers/pcquotation/domain/seller/repository/SellerRepository.kt
  backend/src/main/resources/application.yml
  backend/src/test/java/com/programmers/pcquotation/domain/delivery/controller/DeliveryControllerTest.kt
  backend/src/test/java/com/programmers/pcquotation/domain/estimaterequest/controller/EstimateRequestControllerTest.kt
  backend/src/test/java/com/programmers/pcquotation/estimate/service/EstimateServiceTest.java
  frontend/next.config.mjs
  frontend/package-lock.json
  frontend/package.json
Labels: feature, fix, test
